### ISSUE TITLE
Module bs4 missing

### ISSUE THREAD

**Issue by bushyiv** [kryptxy/torrench#1]
Received this message in my first attempt at testing the script.

guy@guy-HP ~ $ torrench -p 5 "suits s01e01" 
No module named 'bs4'
Please install and retry.

I'm new to Linux, do not know what bs4 is and where to begin to install it.  Assistance is appreciated.

**Comment by DasEarl** [comment]
bs4 or beautiful soup is a html parser for python which is missing on your machine.
https://www.crummy.com/software/BeautifulSoup/bs4/doc/

I guess you already have pip installed. If not install it with
`sudo apt-get install -y python3-pip`

Then install all the packages
`pip3 install request bs4 lxml tabulate termcolor`

Or just bs4 in your case.

**Comment by bushyiv** [comment]
DasEarl
Thanks for helping.  I tried following your suggestions and received some errors.

guy@guy-HP ~ $ pip3 install request bs4 lxml tabulate termcolor
Collecting request
  Downloading request-0.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-o5y2lshb/request/

**Comment by DasEarl** [comment]
Apparently you need to install setuptools by hand:
`sudo apt-get install -y python3-setuptools`

**Comment by bushyiv** [comment]
I guess I am almost there ;-)
After running the install for setuptools and test again I received this error:

guy@guy-HP ~ $ torrench -p 5 "suits s01e01" 
No module named 'tabulate'
Please install and retry.

**Comment by bushyiv** [comment]
Googled for Tabulate, found a install command, used it and got a bunch of RED text back, apparently something didn't go right.  Tried installing it again and the output seemed everything was good, yet when testing I again got the message that Tabulate was missing, very confusing for a noob.

guy@guy-HP ~ $ sudo -H pip install tabulate
Requirement already satisfied (use --upgrade to upgrade): tabulate in /usr/local/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by DasEarl** [comment]
As you can see in the tabulate installation path, tabulate was installed as a Python 2 dependency. You need the Python 3 which needs to be called explicitly.

The following command should install all you need:
`sudo pip3 install request bs4 lxml tabulate termcolor`

**Comment by bushyiv** [comment]
Thanks, looks like everything is now working.

**Comment by kryptxy** [comment]
As mentioned in install instructions.
`$ (sudo) python3 -m pip install requests bs4 lxml tabulate termcolor`

Closing as resolved.
