### ISSUE TITLE
Suggestion: Torrent/Magnet added to torrent client automatically.

### ISSUE THREAD

**Issue by z1lt0id** [kryptxy/torrench#12]
Hey,

A good idea for Torrench would be to have the option to push the torrent or magnet straight to your download client of choice. Transmission has a nice simple API as Deluge has its console application to change things on the fly as well.

It would make the workflow of the application much more streamlined. Rather than downloading the torrent, adding it manually to your client of choice, a black hole directory or manually adding it via a UI.

Just a thought :)

**Comment by kryptxy** [comment]
Hi, 
Though there is an option to add torrent automatically to (default) client, its still not full-proof. Pushing to client of choice will be implemented in future releases. Can't promise when, but it will be soon :)
