### ISSUE TITLE
Config file not configured. Configure to continue. Read docs for more info.

### ISSUE THREAD

**Issue by Roland-Zhu** [kryptxy/torrench#14]
root@develop:~ # torrench -k "game of thrones s07e06"

Config file not configured. Configure to continue. Read docs for more info.

root@develop:~ # uname -a
FreeBSD develop 11.0-STABLE FreeBSD 11.0-STABLE #0 r313908+f4b711d1be8(freenas/11.0-stable): Tue Jun 13 19:17:29 UTC 2017     root@gauntlet:/freenas-11-releng/freenas/_BE/objs/freenas-11-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64

**Comment by kryptxy** [comment]
Download and enable configuration file.
https://github.com/kryptxy/torrench#configuration-instructions

**Comment by kryptxy** [comment]
Closing!
