### ISSUE TITLE
No results for give input!

### ISSUE THREAD

**Issue by dimaspencer84** [kryptxy/torrench#15]
I get this error message for any research from Distrowatch (-d). I downloaded your tool from pip3.
I really like your tool man. Thank you!
Dima

**Comment by kryptxy** [comment]
What's the exact search string entered?

**Comment by dimaspencer84** [comment]
It's case sensitive then. because what I tried was :
`torrench -d 'Ubuntu'`
But, it works now on my side.
Thank you very much.

**Comment by kryptxy** [comment]
I'll fix this in next release. Thanks!
Closing.
