### ISSUE TITLE
support skytorrents

### ISSUE THREAD

**Issue by Docbroke** [kryptxy/torrench#19]
Hi,  
Thanks for this wonderful tool.

I have found that www.skytorrents.in as much more reliable as compared to KAT or TPB, (in my country). It works all the time and doesn't require proxy. Can you add support for that?

Another request is to add support for selecting search categories on TPB or skytorrents if you choose to support it.

Thanks

**Comment by itdaniher** [comment]
skytorrents is great. something along these lines might be useful as a starting point:

```
s = get_lxml_source_tree("https://www.skytorrents.in/search/all/ed/1/?q=query+"+str(i))
page_count = s.xpath('/html/body/div[1]/div[2]/div[2]/div/a')[-1].text
for j in range(int(page_count)):
    print(b.frame.uri()['value'])
    s = get_lxml_source_tree("https://www.skytorrents.in/search/all/ed/"+str(j+1)+"/?q=flac+"+str(i))
    magnets = [x.attrib['href'] for x in s.xpath('/html/body/div[1]/div[2]/div[3]/table/tbody/tr[*]/td[1]/a[3]')]
    nameurl = [(x.text.strip(), 'https://www.skytorrents.in'+x.attrib['href']) for x in s.xpath('/html/body/div[1]/div[2]/div[3]/table/tbody/tr[*]/td[1]/a[1]') if x.text ] 
```

**Comment by kryptxy** [comment]
skytorrents seems good (didn't know about this).
Will add it in the next update.

As for TPB categs, I haven't had any need for category search, so didn't add. I'll see what I can do about it.

**Comment by kryptxy** [comment]
Update: Added skytorrents support in v1.0.5.
Feedback/suggestions are more than welcome.
(Closing!)
