### ISSUE TITLE
Why manipulating the PATH variable

### ISSUE THREAD

**Issue by DasEarl** [kryptxy/torrench#2]
Instead the symlink could directly target /bin/torrench

**Comment by kryptxy** [comment]
You mean creating a symlink in /bin/ instead of altering the $PATH?

**Comment by DasEarl** [comment]
Exactly. My $PATH would be way to long if every program would add its own path to it

**Comment by kryptxy** [comment]
Added symlink option to /usr/local/bin
https://github.com/kryptxy/torrench#requirements-and-installation

Closed!
