### ISSUE TITLE
Changing Torrench licence to MIT

### ISSUE THREAD

**Issue by kryptxy** [kryptxy/torrench#23]
Hi,
Torrench is presently under GPL3 licence. Though there isn't any issue with this one, I have been thinking of changing to MIT licence for one good reason that it's more permissible as compared to GPL3 licence.
Thoughts?

@itdaniher @RajuKshetrimayum @Ricky-Wilson

**Comment by itdaniher** [comment]
BSD would be swell! I prefer it to the GPL for smaller / relatively straight-forward projects, where there's more of a benefit to the network effect of someone using it for its permissive license than cost to a third party (maybe) not contributing their modifications back to the public.

Cheers!

**Comment by kryptxy** [comment]
Makes sense. Just read about BSD licence. Seems like a good fit for this project...

**Comment by kryptxy** [comment]
@Ricky-Wilson @RajuKshetrimayum are you fine with changing torrench licence to MIT?

**Comment by RajuKshetrimayum** [comment]
Yes, i am fine and good luck.

**Comment by kryptxy** [comment]
@datafanatic You fine with changing licence to MIT?

**Comment by datafanatic** [comment]
Yes.
