### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by datafanatic** [kryptxy/torrench#28]
As per #25, it was suggested that perhaps there would be a better way to organize and handle the command line arguments used in torrench. This issue will be used to track the discussion.

https://github.com/kryptxy/torrench/issues/25#issuecomment-331900687 suggested the use of `docopt` and `click`. Personally, I have found `click` easier to use and simpler to read. 

Are there any better alternatives? Also, perhaps we could also consider a re-factorization of the code, instead of changing the module used to parse the CLI arguments.

**Comment by nicolasmsg** [comment]
Hello, i just rewrite the application using click. I tried to do it with the less changes possible,
tell me what you think. With some re factorization it could be really great i think. 

https://github.com/nicolasmsg/torrench/tree/migrationToClickCLI/torrench
