### ISSUE TITLE
error installing.

### ISSUE THREAD

**Issue by arnauldb** [kryptxy/torrench#29]
Hello,

when installing on Ubuntu with:

> sudo python3 -m pip install --upgrade torrench

I have this:

> Collecting pyperclip (from torrench)
>   
>  Downloading pyperclip-1.5.27.zip
>     Complete output from command python setup.py egg_info:
>      
>      ----------------------------------------
> Command "python setup.py egg_info" failed with error code -11 in /tmp/pip-build-g6v2lrfl/pyperclip/

thank you for any help.

**Comment by datafanatic** [comment]
Hi @arnauldb - what is your operating system? Have you updated `pip` itself? Is this the first time that this is happening?

**Comment by arnauldb** [comment]
> what is your operating system?

Ubuntu Zesty Zapus

> Have you updated pip itself?

yes, $pip --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)

> Is this the first time that this is happening?

yes.

**Comment by kryptxy** [comment]
1. Try running ```sudo python3 -m pip install --upgrade pip``` and then run ```sudo python3 -m pip install torrench```. If this does not work, go to 2.
2. Try installing ```pyperclip``` separately. ```sudo python3 -m pip install pyperclip```. Then install torrench. See if this works (and report?)
3. If above does not work either - try ```sudo pip3 install --upgrade torrench``` (Do run the pip3 upgrade first to upgrade pip3 to latest version)
4. If this does not work either, revert!

**Comment by arnauldb** [comment]
1 & 2 didn't work, I have the same error message:

> Collecting pyperclip
>   Downloading pyperclip-1.5.27.zip
>     Complete output from command python setup.py egg_info:
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code -11 in /tmp/pip-build-faxzqnf3/pyperclip/

3 didn't work either.

If I build from source using

> sudo python3 setup.py install

how do I launch torrench ?

**Comment by kryptxy** [comment]
> how do I launch torrench ?

The way other CLI programs are run (```$ torrench -h```)

**Comment by arnauldb** [comment]
ok. Thank you. I didn't succeed installing torrench on my machine, but I installed it successfully on my other computer, I guess it's a problem with me not torrench.

**Comment by kryptxy** [comment]
(Closing)
