### ISSUE TITLE
Error message: Can't convert 'NoneType' object to str implicitly

### ISSUE THREAD

**Issue by Nolent** [kryptxy/torrench#30]
Hi, I have this error when i try to use torrench with Kat.

`[KickassTorrents]

Obtaining proxies...
Trying https://kickass.cd/
Available!

Fetching from page: 1
Page fetched!
Error message: Can't convert 'NoneType' object to str implicitly
Something went wrong! See logs for details. Exiting`

I don't know where I can find the logs^^ I'm using ubuntu 16.04

**Comment by kryptxy** [comment]
https://github.com/kryptxy/torrench/blob/master/README.md#note
(Bullet #2)

KAT proxies are having some issues. You may use TPB/SkyTorrents/XBit till the proxies are up again.
