### ISSUE TITLE
Feature request: enable multiple tracker merged results

### ISSUE THREAD

**Issue by nodje** [kryptxy/torrench#31]
Hi, 

great job, this is cool & fun to use.
A feature that would add great value to the tool that comes to mind immendiately would be to be able to merge result from different trackers.
I.e., being able to do `torrench -tks "my search"`

**Comment by kryptxy** [comment]
> A feature that would add great value to the tool that comes to mind immendiately would be to be able to merge result from different trackers.

I got similar suggestion from other users. Have begin working on same. Next update should have this (no promises though).

**Comment by kryptxy** [comment]
Update: Cross-site support added.
https://github.com/kryptxy/torrench/issues/65

(Closing this issue)
