### ISSUE TITLE
Torrentch.exe not recognised as executable in comand prompt (Windows 7)

### ISSUE THREAD

**Issue by JPC1941** [kryptxy/torrench#32]
Hi,
I followed these instructions
Windows: Default config file location is C:\Users\<user>\config\torrench \
_>>> Creating .config directory:_
1. Create a new directory named "config" (In C:\Users\<user> \)
2. Right-click the directory -> Select 'Rename'
3. Add a dot (.) In the beginning and at the end of filename (means "config" becomes ".config.")
4. Save. This should create a required (.config) directory.
5. Create 'torrench' directory inside (.config) directory (the usual way).
_>>> Next, enable config file and copy it to .config\torrench\directory. That's it!_

Then I copied "torrench-1.0.54.exe" into this directory: 'C:\Users\JPC\.config\torrentch\torrench.exe'
So now, in C:\Users\JPC\.config\torrentch, there are:
- config.ini  (with enable = 1)
- torrentch.exe

_In a command prompt in administrator mode,_
I'm testing :
C:\Users\JPC\.config
       $ torrentch --help
      'torrentch' is not recognized as an internal command or external, an executable program or a batch file.
_Another test in other directory:_
C:\Users\JPC\Desktop\TorrentCh> torrentch-1.0.54 --help
     'torrentch-1.0.54' is not recognized as internal command or external, an executable program or a batch file.
_So...
What do you think about it?
Where to put the <torrentch.exe> ​​or <torrentch-nnn.exe> ​​executable?_

Please, note that torrentch.exe or torrench-1.0.54 do not have an owner and are not editable
****
![visu](https://user-images.githubusercontent.com/32432696/31054649-873d164c-a6b7-11e7-8dfd-f445c31c6212.png)

**Comment by JPC1941** [comment]
Oups, I'm so sorry !

I wrote torrentch, NOT torench !
I think it will work fine now...

**Comment by kryptxy** [comment]
Is it resolved?

**Comment by JPC1941** [comment]
Yes, it works, except for the options -t, -k, -s, -n and -x where the config.ini is considerated as absent or invalid :

	_With : C:\Users\JPC\.config\torrentch>torrench -d 'solus' :_
[DistroWatch]
Fetching results...
+--------------------------------------------------------+---------+------------+
| NAME                                                   | INDEX   | UPLOADED   |
+========================================================+=========+============+
| solus-3-budgie.iso.torrent                             | --1--   | 2017-08-15 |
+--------------------------------------------------------+---------+------------+
| solus-2017.04.18.0-budgie.iso.35532f8160529469.torrent | --2--   | 2017-04-20 |
+--------------------------------------------------------+---------+------------+
| solus-2017.01.01.0-budgie.iso.03476572364d397b.torrent | --3--   | 2017-01-05 |
+--------------------------------------------------------+---------+------------+
| solus-1.2.1.iso.337fca8d4cf7b4d3.torrent               | --4--   | 2016-10-21 |
+--------------------------------------------------------+---------+------------+
| solus-1.2.0.5.iso.0afb72b9839d4b00.torrent             | --5--   | 2016-09-08 |
+--------------------------------------------------------+---------+------------+
| solus-1.1.iso.99a1b2c2253304f2.torrent                 | --6--   | 2016-03-03 |
+--------------------------------------------------------+---------+------------+
| solus-1.0.iso.92f811d6933ec150.torrent                 | --7--   | 2016-01-01 |
+--------------------------------------------------------+---------+------------+

	_...but with : C:\Users\JPC\.config\torrentch>torrench -t 'solus'_

Config file not configured. Configure to continue. Read docs for more
Config file either does not exist or is not enabled! Exiting!

	_I think it's because of this (wrong or out of service adresses in config.ini ?) :_

TPB_URL = https://thepiratebay.org https://proxybay.one
SKY_URL = https://www.skytorrents.in
NYAA_URL = https://nyaa.si/
XBIT_URL = https://xbit.pw/

Thanks a lot
JPC1941

PS 
Is it possible to use wildcards (e.g. 'solus*' or game.of.thrones*'

**Comment by kryptxy** [comment]
The config file is not found/configured.
I see a typo.
The directory name is ```.config\torrench```
 ```C:\Users\JPC\.config\torrench\```

**Comment by JPC1941** [comment]
Oh Yes, It's all folks !
Thank you so much !

**Comment by Princeyadav05** [comment]
Hey @kryptxy 
I'm having same error.
```
PS C:\Users\Prince\.config\torrench> torrench --help
torrench : The term 'torrench' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ torrench --help
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (torrench:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException```

**Comment by kryptxy** [comment]
@Princeyadav05 did you rename the file to ```torrench.exe``` and moved the downloaded file to ```.config\torrench``` folder? If not, go to folder where ```torrench-1.0.XX.exe``` is present and then run the exe from CMD/Powershell.

**Comment by Princeyadav05** [comment]
working now. Thanks bro.
