### ISSUE TITLE
No config (torrench.ini) file found

### ISSUE THREAD

**Issue by Princeyadav05** [kryptxy/torrench#35]
Hey @kryptxy 
I was using torrench on windows without any problem.
But on linux it is returning this 
```
Option [p/l]: l
No config (torrench.ini) file found!
```

when I'm trying to load the torrent.

Provided below are the scrrenshots of my 
1. .config/torrench folder.
2. Terminal 
3. config.ini file
![screenshot from 2017-10-03 13-33-32](https://user-images.githubusercontent.com/22894003/31115321-782c832a-a83f-11e7-87c0-2d55e8e38684.png)
![screenshot from 2017-10-03 13-33-54](https://user-images.githubusercontent.com/22894003/31115330-858e2500-a83f-11e7-9294-41ad27eccd55.png)
![screenshot from 2017-10-03 13-35-21](https://user-images.githubusercontent.com/22894003/31115393-c101ee64-a83f-11e7-8296-65c86c8f3e91.png)

**Comment by kryptxy** [comment]
https://github.com/kryptxy/torrench/blob/master/CHANGELOG.md#28092017-v1054

**Comment by Princeyadav05** [comment]
Hey. @kryptxy Thank you so much. Its working again.
And I've used the deluge-gtk client. Beacuse you asked to inform on some new clients.
Also, I know some more torrents like extratorrent and 1337x.

**Comment by kryptxy** [comment]
> And I've used the deluge-gtk client

Thanks.
Closing! (Please consider opening a new issue for a different subject if required)
