### ISSUE TITLE
MacOS torrentch.ini

### ISSUE THREAD

**Issue by afk-mcz** [kryptxy/torrench#38]
When I try to load the magnet link on client I get the following error.

`[ERROR]: [Errno 2] No such file or directory: 'transmission': 'transmission'`

I tried with transmission-remote, transmission-gtk, transmission-qt and had the same result.

**Comment by kryptxy** [comment]
Is transmission-{remote,gtk,qt} accessible from terminal?

**Comment by Arlefreak** [comment]
I have to use the full path

`/Applications/Transmission.app/Contents/MacOS/Transmission`

Loading the magnet link on the client was working before the need for a thorrentch.ini

**Comment by kryptxy** [comment]
What's the output for ```$ transmission-gtk```?

If you are using full path, it means transmission is not in your environment (PATH). Try figuring out what your $PATH has maybe?

**Comment by Arlefreak** [comment]
I added Transmission to my PATH, but now it opens a new instance of transmission every time and doens't load the magnet link, is there a way to make the browser handle it ? like on windows?

**Comment by kryptxy** [comment]
> I added Transmission to my PATH, but now it opens a new instance of transmission every time and doens't load the magnet link

Can you please attach the log file. As per reports from users, it works fine. Does ```$ transmission-gtk``` open the transmission GUI window?

> is there a way to make the browser handle it

As of now there isn't. I'll add the browser option.

**Comment by kryptxy** [comment]
Closing issue as no response.
