### ISSUE TITLE
Documentation Request: Supports filtering search using categories

### ISSUE THREAD

**Issue by z1lt0id** [kryptxy/torrench#4]
I was wondering if you could go into detail how you exactly you do a filtered search using categories in regards to TPB? 

Would it be something like:

`torrench -t "Movies - HD 2160p"` (??)

**Comment by kryptxy** [comment]
Category filters are not supported yet. 
Bu default, results are fetched from all.

**Comment by z1lt0id** [comment]
Good to know - thanks for that update.
