### ISSUE TITLE
tracker request: idope.se

### ISSUE THREAD

**Issue by itdaniher** [kryptxy/torrench#45]
pretty self-explanatory; depending on schedule I might take a stab at it.

urls are of the form:

`https://idope.se/torrent-list/ubuntu/?p=2`

and it looks like results are just

`//*[@id="hideinfohash0"]` zipped with `//*[@id="hidename0"]`

cheers!

**Comment by kryptxy** [comment]
Nice. Will add this :)

**Comment by kryptxy** [comment]
Site is using Javascript (ALOT). Everything is done, except Magnetic URI. Magnetic URI is loaded with JS - and not only the URI but the tag its getting data from is loaded with JS (as python ```requests``` module is unable to capture it). Got any ideas/work-around?

**Comment by datafanatic** [comment]
Use PhantomJS. It's a little heavier than pure Requests + BS4 but it will do the job. I'm currently working on a C++ project, but I'll tackle it during the weekend if there's no progress.

**Comment by itdaniher** [comment]
Shucks, I did not realise the HTML was built with JS at load-time. That's awful. I just wrote those xpaths after poking around with web-inspector in Firefox. I strongly recommend just abandoning this.... there're other things to do, and while PhantomJS would totally work, it strikes me as overkill.

I might spend some time reversing their javascript and seeing if I can't make a pure python script spit out magnets and whatnot, but seriously, don't sweat it. My bad!

**Comment by itdaniher** [comment]
> Shucks, I did not realise the HTML was built with JS at load-time. That's awful. 

It's not the case!

They just check the User-Agent header.

Try:

     curl 'https://idope.se/torrent-list/ubuntu/?p=2' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) Chrome/61.0.3163.100 Safari/537.36' --compressed | grep info

**Comment by kryptxy** [comment]
Ah! Perfect. It worked! I had no idea it would be checking the user-agent. Thanks! How did you diagnose this? Just curious.

Will add idope within this week.

**Comment by itdaniher** [comment]
Just messing around in network inspector - "copy as curl" followed by some process of elimination where I stripped down headers until it stopped returning data.

**Comment by kryptxy** [comment]
Nice. Thanks!

**Comment by kryptxy** [comment]
Idope module added (`master` branch). Please build from source and update the config.ini file accordingly.
