### ISSUE TITLE
Be less verbose!

### ISSUE THREAD

**Issue by lf-araujo** [kryptxy/torrench#47]
Thanks for the excellent tool.

There is too much output being printed, I think that there are several ways of conveying the information without being so verbose. Especially regarding the table divisions, its use is excessive flooding the output of informationless markings.

I would recommend consider using a markdown style of table like the below:

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

**Comment by kryptxy** [comment]
Can you please elaborate a bit more? What table info is not useful? And what all verbose can (or should) be removed?

Table output style can be changed, but other styles were making the content less readable.

**Comment by lf-araujo** [comment]
Sure,

Being more specific. The element the user will want to be presented unobstructed is the index and the name, I would suggest changing the order of the table so that the index is printed first.

Second, please consider the following:

![](https://github.com/kryptxy/torrench/raw/master/images/screenshots/ubuntu.png)

See the horizontal divisions? These are overused, in the end they are not helping organizing the data you want to present. Instead they become clutter, because one has to scroll far more than needed to the end of the list. There are several ways of avoiding that, the structure in my last comment is the one I think is the clearest.


Finally, please consider the following:

![](https://github.com/kryptxy/torrench/raw/master/images/screenshots/1337x.png) 

In this one, the output would benefit of some changes. You could present SE/LE in one column, you could present the date in a shorter format like DD/MM/YY. 

A few less important suggestions: I would lose the C column (the last one) and the category column (perhaps giving the user the chance of filtering by category).

Thank you!

**Comment by prakashdanish** [comment]
> Being more specific. The elements the user will want to be presented unobstructed are the index and the name, I would suggest changing the order of the tables so that the index is always printed first. Also lose the two dashes before and after (--1--).

> In this one, the output would benefit of some changes. You could present SE/LE in one column, you could present the date in a shorter format like DD/MM/YY.

Agree with @lf-araujo on this. If you approve these potential changes @kryptxy I'd like to give it a shot.

**Comment by kryptxy** [comment]
> Being more specific. The elements the user will want to be presented unobstructed are the index and the name, I would suggest changing the order of the tables so that the index is always printed first. Also lose the two dashes before and after (--1--).

@lf-araujo I tried with index printed first - but when choosing torrents, referring index for each torrent is a bit more convenient when index is placed after torrent name. (I tried both - and this order was more helpful (for me) when selecting torrent). Same reason for the two dashes.
This being said, The order you are suggesting, give it a try - and show me? It's a pretty simple fix - I can walk you through the changes required. Let me know if you want to.

> See the horizontal divisions? These are overused, in the end they are not helping organizing the data you want to present. Instead they become clutter, because one has to scroll far more than needed to the end of the list.

I used the [tabulate](https://pypi.python.org/pypi/tabulate) module to print results. This style suited me the best, and actually never though of changing it. But yes - I agree. This can be improved. I'll look into it when I'll get some free time. 
Till then if you'd like to give it a try - the ```tablefmt``` parameter [here](https://github.com/kryptxy/torrench/blob/master/torrench/utilities/Common.py#L150)
parameter needs to be changed (that's it). Supported table formats are available in [tabulate's documentation](https://pypi.python.org/pypi/tabulate). If you do try something out, let me know :)

> you could present the date in a shorter format like DD/MM/YY.

Upload dates are printed as they are fetched from the website. Some sites have DD/MM/YY format, some don't. I do not alter any of data fetched from websites.

> You could present SE/LE in one column

Yes. This would be great. Thanks. 
@prakashdanish you may give this a shot. Ping me if you need any help :)

**Comment by kryptxy** [comment]
@prakashdanish any update?

**Comment by prakashdanish** [comment]
@kryptxy will do it soon, got stuck in college work :/

**Comment by lf-araujo** [comment]
I cant help out at the moment... but thanks for your help!
