### ISSUE TITLE
setup.py minor Linux standardization

### ISSUE THREAD

**Issue by ad33329** [kryptxy/torrench#49]
setup.py does not have the executable bit. Is it possible for you to have it set in the repo by default?

Also, I should point out, not everyone has their Python binary in `/usr/bin/python3` (e.g., if you compiled Python from source, it might be in `/usr/local/bin`) -- better compatibility is probably something like `#!/usr/bin/env python3`.

Note: I don't use Mac or anything and don't know if the `/usr/bin/env` thing works with their environment. Should probably test before applying this change. But I CAN confirm it works with Cygwin, Debian, Ubuntu, and Arch Linux.

**Comment by kryptxy** [comment]
> setup.py does not have the executable bit. Is it possible for you to have it set in the repo by default?

What exactly do you mean by executable bit?

> Also, I should point out, not everyone has their Python binary in `/usr/bin/python3` (e.g., if you compiled Python from source, it might be in `/usr/local/bin`) -- better compatibility is probably something like `#!/usr/bin/env python3`.

Yes I know using `/usr/bin/env` is better. But I myself do not own any Mac hardware. So wasn't able to test this. So I kept `/usr/bin/python3`.
If someone could confirm if it works or not, I would be able to implement this change.

**Comment by ad33329** [comment]
Oh. Sorry. I forgot to check my account for like 2 weeks. That happens sometimes. :stuck_out_tongue: 

Note to self: see if you can find some sort of RSS feed mechanism to get decent notifications for when you get messages on Github.

I have a family member who uses a Mac computer, but I won't be able to borrow hers for a couple months. I could try it on there sometime. Alternatively, I could set up a Mac OS X VM on one of my higher end machines as a testbed -- which is probably a good general thing for a dev to do when they have decent hardware. :stuck_out_tongue: 

I'm 90% sure that Mac has `/usr/bin/env`. It seems to have a lot of the standard Linux stuff, surprisingly enough. But I will try to find one of my old Mac OS X DVDs, so I can pull apart the directory structure and see if I can find a `env` executable. Not sure what your standard of evidence is here, but that seems like it ought to be a sufficient initial guess. If there is an `env`, it probably works the same basic way as our `env`, possibly with the exception of different involved syntax since it's likely BSD based. (Since we're using trivial syntax in this implementation, that shouldn't be relevant.)

I will investigate this one way or another, and let you know what I find.

As for 'executable bit'...

I don't know how much you know about Unix architecture, so I'll just cover most of it here. Sorry if you already know some of this stuff. I'm not trying to be patronizing.

Anyway, the executable bit is the thingy that lets the Linux kernel know that a file is executable. It's part of all Unixlike OS filesystems, as far as I know. If you do `ls -la`, you can see the executable bit as `x`. The syntax 'rwxrwxrwx' tells you the permissions (Read-Write-Execute) of the file for 3 different categories: the owner of the file, users who are part of the group owning the file, and everyone else. This information is actually stored as a few magic bits in the file, I think, judging from how people talk about them. Or maybe they're stored in the file table itself. (The thingy that stores the names of all the files, and where they begin and end). Anyway, the internals don't matter much to how the tools are used, which I suppose is why I don't know that much detail about that. :stuck_out_tongue_closed_eyes: 

So, if you see a file that has `rwx------`, that means the owner can read/write/execute, but the group and all other users can't do shit to it. And if you see `rw-------`, it means it's read/writable, but not marked as executable.

When dealing with directories, the executable bit determines whether or not the directory can be viewed. I'm honestly not sure why this is a feature, as I find it annoying when doing recursive permissions changes, and I've never ever needed to remove the executable bit on a directory when I can simply remove the readability bit.  From what I can tell, it's an entirely redundant feature.

When dealing with files, the executable bit determines whether or not you can call the file, just by doing `./[file name]`. In the case of your `setup.py`, the user is forced to call `python3 setup.py` instead, because you don't have the executable bit. To fix this, simply do `chmod +x setup.py`, (which tells the filesystem to allow the _owner_ of setup.py to pass it to the kernel as an executable) and then push to git (assuming you are working in a Unixlike environment -- if you're on Windows and not using Cygwin, I'm not sure how to fix this).

On a side note, these permissions are also retained when you zip a file up into a tar, which is why so many Linux devs prefer to distribute software as .tar files instead of .zip files. (Also, there's the fact that a tar container doesn't attempt compression in and of itself, so you can pair it with any other zip compression algorithm, depending on the contents -- e.g., tar.zip, tar.gz, tar.7z...).

See [the Wikipedia article on Unixlike traditional file system permissions](https://en.wikipedia.org/wiki/File_system_permissions#Traditional_Unix_permissions) for more information.

**Comment by kryptxy** [comment]
Wow. Thanks for detailed info. I do know about linux's `x` bit and about file's/directory's `rwx` properties.

> I will try to find one of my old Mac OS X DVDs, so I can pull apart the directory structure and see if I can find a env executable.

Any luck?

The setup.py file does have the required [shebang](https://github.com/kryptxy/torrench/blob/master/setup.py#L1) to run file as `./setup.py`. If I am not wrong, the [umask](https://docs.oracle.com/cd/E19683-01/817-3814/userconcept-95347/index.html) utility sets the default permissions assigned to any (new) file or directory. As you mentioned, file can be accessed as `./setup.py` by changing it's permissions (Example: `chmod a+x setup.py`)

**Comment by kryptxy** [comment]
(Closing as no response)

**Comment by ad33329** [comment]
@kryptxy  Aww crap. I totally forgot about this. Sorry. I have like 3 part time jobs. :(

I'll reopen later when I have more time to dedicate to github, maybe?
