### ISSUE TITLE
New module to download torrents from DistroWatch

### ISSUE THREAD

**Issue by slicer69** [kryptxy/torrench#5]
As DistroWatch also supplies legal ISO files, much like LinuxTracker, I have put together a new module that finds and downloads torrents from DistroWatch. The attached patch adds the module and the command line parameters "-d" and "--distrowatch" to specify the site as a search options.

[torrench-add-distrowatch.txt](https://github.com/kryptxy/torrench/files/1220011/torrench-add-distrowatch.txt)

**Comment by kryptxy** [comment]
I'll look into it and revert.

**Comment by kryptxy** [comment]
Sorry for reverting back this late. Was occupied with college stuff. 
Thanks for distrowatch module. I have applied the patch, and also added upload date to it. 
Sources updated.

**Comment by slicer69** [comment]
Thank you.
