### ISSUE TITLE
TR_AUTH not set

### ISSUE THREAD

**Issue by smanull** [kryptxy/torrench#51]
Hi,

I am facing an error when trying to load the magnetic link to the transmission-remote client. 

```[ERROR] The TR_AUTH environment variable is not set```

In my transmission-daemon settings.json authentication is set false: `"rpc-authentication-required": false,` and in torrench.ini I did not specify `TR_AUTH`. I am not sure whether this is a transmission or a torrench issue.

Any help is appreciated! Thanks in advance!

**Comment by datafanatic** [comment]
`TR_AUTH` is an environment variable. If you are on a UNIX-like environment, to set it you'll do `export TR_AUTH=user:password`. Also, you need to enable remote management. Go to the transmission GUI > Edit > Preferences > Remote and mark the "Enable remote access" box. Then, mark the "Use authentication" box, choose a login and password then use those in the `TR_AUTH` environment variable. i.e. `export TR_AUTH=smanull:smanull`.

**Comment by smanull** [comment]
Wow, thanks a lot for the very fast and helpful reply! Your solution works perfectly!
