### ISSUE TITLE
Mac OS Config Location?

### ISSUE THREAD

**Issue by Gillinghammer** [kryptxy/torrench#53]
Not sure if I have my config file in the right place on Mac... getting the following when running an example query :

`Traceback (most recent call last):
  File "/usr/local/bin/torrench", line 9, in <module>
    load_entry_point('torrench==1.0.56', 'console_scripts', 'torrench')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/torrench/__main__.py", line 8, in <module>
    import torrench.Torrench as Torrench
  File "/Library/Python/2.7/site-packages/torrench/Torrench.py", line 7, in <module>
    from torrench.utilities.Config import Config
  File "/Library/Python/2.7/site-packages/torrench/utilities/Config.py", line 4, in <module>
    from configparser import SafeConfigParser
ImportError: No module named configparser`

**Comment by datafanatic** [comment]
Try:

`sudo pip3 install configparser`

**Comment by Gillinghammer** [comment]
Thanks @datafanatic - tried it but no luck, same error here

**Comment by datafanatic** [comment]
What was the output of the command (the one I sent you)?

**Comment by Gillinghammer** [comment]
@datafanatic 
```
The directory '/Users/gillinghammer/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/gillinghammer/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting configparser
  Downloading configparser-3.5.0.tar.gz
Installing collected packages: configparser
  Running setup.py install for configparser ... done
Successfully installed configparser-3.5.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by datafanatic** [comment]
Ok. First upgrade pip as the message said. How did you install torrench? Was it from the repository or pip?

**Comment by datafanatic** [comment]
Also, please post the output of `python -V`

**Comment by Gillinghammer** [comment]
Not sure the upgrade command is working for me, shows me:
`Requirement already up-to-date: pip in /Library/Python/2.7/site-packages`

python -V: 
`Python 2.7.10`

**Comment by datafanatic** [comment]
That's the problem. Torrench only works with Python 3+. Post the output of this command: `python3 -V`.

**Comment by datafanatic** [comment]
Also, `pip` and `pip3` refer to different versions, Python 2.x and Python 3.x, respectively. What you should do is `sudo pip3 install --upgrade pip`.

**Comment by kryptxy** [comment]
As @datafanatic mentioned, torrench works with python3+. 

> Traceback (most recent call last): File "/usr/local/bin/torrench", line 9, in <module> load_entry_point('torrench==1.0.56', 'console_scripts', 'torrench')() File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point return 

Traceback shows torrench is installed using python2. Please remove the 2.7-installed version and re-install it using python3.
`$ sudo pip3 install --upgrade torrench`

**Comment by Gillinghammer** [comment]
@datafanatic and @kryptxy 
thanks for helping this Noob - All good now, cheers.
