### ISSUE TITLE
Possible bug in the Nyaa module

### ISSUE THREAD

**Issue by datafanatic** [kryptxy/torrench#55]
I was testing a couple of things earlier today and there seems to be a malfunction with the nyaa module. Ex:

`$ torrench -i`
`$ torrench > !n "monster 2004"`
gives 
`Unable to parse torrent name.`
but
`$ torrench > !n monster 2004` works and so does `$ torrench > !n 'monster 2004'`. But double quotes do not seem to work at all.

To me it seems like it's parsing quoted names in an incorrect way. Since I have written the nyaa module, I'll take responsibility and try to have it fixed until the end of the week. Figured I'd let any other users know.

**Comment by kryptxy** [comment]
> But double quotes do not seem to work at all.

I tried a few searches and double quotes did work in some. Example: try "death note".

I found one more (minor) bug. In case no results are found, it gives `Unable to parse torrent name.`
Since you will be reviewing nyaa module, maybe you could have a look at this too?

**Comment by datafanatic** [comment]
Yes, I shall take a look at it. Thanks.

**Comment by datafanatic** [comment]
It seems like the problem in mentioned in the OP is not really a problem with the module itself, rather, the way that the search works in the website. Double quotes are treated as literals, much like Google does in their search engine. It would be possible (and trivial) to remove double quotes from queries before calling the module but I thought about letting them for users who may want specific results. 

For example:
`$ torrench > !n monster` will print all torrents that contain the string "monster"
`$ torrench > !n monster tv` will print all torrents that contain the strings "monster" and "TV" but
`$ torrench > !n "monster tv 2004"` will print the only result which exactly matches the query. 
`$ torrench > !n "monster tv"` will also print torrents with different names, but always matching the convention used in the search. What do you think?

**Comment by kryptxy** [comment]
Removing double quotes is preferable. Cause torrents matching search keywords is more likely to give intended result. In case of specific search (IMO) not every torrent would have the exact name as we'd type. And even though the torrent we are looking for is present, it would give no results.

**Comment by datafanatic** [comment]
OK. I'll modify the PR soon.
