### ISSUE TITLE
Adding deluge to config

### ISSUE THREAD

**Issue by davidmthomsen** [kryptxy/torrench#58]
I added deluge in the torrench.ini 
CLIENT = `deluge`
 However it gets error when I try to Load magnetic link to client
[ERROR]: [Errno 2] No such file or directory: '`deluge`'

I am using Mac OS X.

**Comment by davidmthomsen** [comment]
I got it fixed, I set the absolute path to deluge
/Applications/Deluge.app/Contents/MacOS/Deluge

**Comment by kryptxy** [comment]
Closing as resolved.
