### ISSUE TITLE
Feature request: Library Genesis?

### ISSUE THREAD

**Issue by payasrelekar** [kryptxy/torrench#59]
[Library genesis](libgen.io) has torrents for most of the books [here](http://gen.lib.rus.ec/repository_torrent/). I have no idea how we can search that as torrents don't seem to be named by book/author/publisher. Just want to see if there is a possibility whether this can be utilized for torrench.

Libgen mirrors in case it is blocked in your country: [1](gen.lib.rus.ec), [2](libgen.pw), [3](bookfi.org).

**Comment by kryptxy** [comment]
Most of the torrents are dead (I tried some, and all were dead).

**Comment by payasrelekar** [comment]
Ok, I may not have checked that. However, I went ahead and searched for couple of books, and torrent links on individual book pages work just fine. Can we scrape from that? Also, I don't understand how it works, but they have an API, with a description on their [forums](https://genofond.org/viewtopic.php?f=17&t=6874)(requires registration, pdf of the page [here](https://www.pdfhost.net/index.php?Action=Download&File=219baab2e21fc7f4f65dc1561083f700)).

**Comment by kryptxy** [comment]
I'll look into it.

**Comment by kryptxy** [comment]
Sorry for late response. Exams are about to start :S

Yes. Torrents do work. Took about 4-5 mins to start.
I tried the API. I see it does not allow to search using book title. Instead, books can be queried either using ID or book ISBN.
To search by title, the site would have to be scrapped. Though its not a lot of work, I feel searching by book ISBN would give more appropriate results. I tried a few queries, and they worked fine. In case book is not available, ISBN would give no results. When same book is searched by title (on site), it produced similar results, but not the one I wanted (of course).

[(Example query)](libgen.io//json.php?isbn=1593272901&fields=Title,Author,Extension,md5,FileSize)
You can try a few queries by modifying the isbn parameter.

The book's ISBN can be obtained using simple google search, or from amazon (This is one extra step user needs to carry out).

Which of the two ways is preferrable? Thoughts?

**Comment by payasrelekar** [comment]
Thanks a lot. ISBN search is good enough, especially if it is less work. Does API provide any other download than torrent? That should speed up whole process a lot, and then it won't matter much if user has to take an extra step.

On second note, once this is in, site scraping can be planned long (long long) term, because that will expose many more options, extensions, sizes and mirrors.

PS: All the best for exams!

**Comment by kryptxy** [comment]
> Does API provide any other download than torrent?

Direct download can be implemented as well, but that's out of torrench's scope.
I don't think torrents should be an issue though. They do take some time to load, but they work. (Also, it would be possible to directly add torrent to client from torrench).

> On second note, once this is in, site scraping can be planned long (long long) term, because that will expose many more options, extensions, sizes and mirrors.

The only thing API does not allow is search ability by title. Rest most of the book info can be made available through API. Title, Author, date, extension, size, description, etc.
The only thing scrapping would provide is ability to search using book title.

**Comment by payasrelekar** [comment]
Fair enough. ISBN it is, then. If at some point there is enough demand for title search through torrench alone, you can think of site scraping. For now, API is good enough.

**Comment by kryptxy** [comment]
> If at some point there is enough demand for title search through torrench alone, you can think of site scraping

Yes definately.

I have updated sources adding libgen (`torrench -g <ISBN>`). You can try it out by building torrench from source till I release the next update (will be released soon).
Do update the config.ini file for libgen to work.

**Comment by kryptxy** [comment]
Update: New release has been published. Update torrench to v1.0.58 and you should be good :) [Sample](https://github.com/kryptxy/torrench#libgen-examples-ebooks).
