### ISSUE TITLE
Feature proposal : Docker container Multiarch

### ISSUE THREAD

**Issue by jaymoulin** [kryptxy/torrench#60]
In order to ease torrench Docker usage, consider building Docker Multiarch image now that hub.docker.com registry is compatible with manifest (https://docs.docker.com/registry/spec/manifest-v2-2/)

So you could be able to `docker run --rm -ti jaymoulin/torrench` instead of `docker run --rm -ti jaymoulin/rpi-torrench:pc` for PC and `docker run --rm -ti jaymoulin/rpi-torrench:rpi` for Raspberry PI

**Comment by kryptxy** [comment]
Thanks for your work. 
I tried pulling the docker image using `docker pull jaymoulin/torrench` (as mentioned on the right hand side of docker repository webpage) . It gave an error - `no matching manifest for linux/amd64 in the manifest list entries`.
However, command `docker pull jaymoulin/torrench:0.2.0-amd64` worked fine. Is this how it is suppose to work? I see `latest` tag in docker repo. If I am not wrong, shouldn't `docker pull jaymoulin/torrench` download appropriate (the latest) image automatically? Am I missing something?

**Comment by jaymoulin** [comment]
My bad, typo
