### ISSUE TITLE
Re-writing Nyaa module

### ISSUE THREAD

**Issue by kryptxy** [kryptxy/torrench#63]
@datafanatic I am in process of introducing cross-site search in torrench. However Integrating the nyaa module is becoming a little difficult, as it shares a completely different structure than other modules. It would have to be re-written in same format as the other modules (TPB/KAT...) to integrate it. 
Since you authored the Nyaa module, I thought to run it by you before I proceed. I hope its fine by you?

**Comment by datafanatic** [comment]
Yeah, go ahead. I started rewritting it myself, but I have the bad habit of doing too many things at the same time so I completely forgot about it. The structure of the website is pretty annoying so it led to some bad design choices from me.

**Comment by kryptxy** [comment]
Its done. It now supports searching through pages too ;)
