### ISSUE TITLE
Config.ini unreachable

### ISSUE THREAD

**Issue by utkudarilmaz** [kryptxy/torrench#68]
I can not download config.ini files. The url is broken. Please do you change config.ini file's url?

**Comment by datafanatic** [comment]
Are you sure? This is the URL provided: https://pastebin.com/raw/reymRHSL and seems to work fine here.

**Comment by kryptxy** [comment]
@utkudarilmaz Hope it's resolved now?

**Comment by utkudarilmaz** [comment]
Sorry, but I can not reach pastebin.com domain. Perhaps this problem is related to my ISP. Would you add another url?

**Comment by kryptxy** [comment]
Here: http://pasted.co/f03417ce

**Comment by utkudarilmaz** [comment]
Thanks a lot.
