### ISSUE TITLE
The beginning....

### ISSUE THREAD

**Issue by itdaniher** [kryptxy/torrench#8]
Hey @kryptxy kryptxy, sweet project! I started hacking around a little bit today to use your scrapers as a source of magnet links for my toy torrent search engine, and have a few thoughts. Take these with a grain of salt, from someone who's written a lot of opinionated Python. I'm writing in a hope that some of these might be useful as you continue to explore the excellent Python ecosystem!

Formatting:
 * [PEP8](https://www.python.org/dev/peps/pep-0008) is the de-facto styleguide for Python code. It's not universal, but it's generally recommended. The first thing I did before I could reasonably edit the project in vim was to zap your torrench codebase with [autopep8](https://github.com/itdaniher/torrench/commit/65df9268b738b74c28c856b3587d5f3c0ceb0b44) to get spaces and tabs as my editor was expecting.

Python stuff:
* Destructuring: I've noticed a few places where you can reduce the number of lines by taking advantage of Python destructuring, like I did [here](https://github.com/itdaniher/torrench/commit/6820cf5db2fa58ef71b7cd6500c1dd8ed0a8ada8)
* Relatedly, you can use Python `int`s as indexes into a dict - `{1: ('name', 'magnet', 'torrent_url')}` is also a valid construct, so even if you don't change the dict to a list/array, you can still collapse those three variables to one and lose the `str()` calls to your keys / indexes.
* Classes: as you've noticed, Python's really nice about letting you fake object-oriented programming by building independent files and using modules as classes. Even with file-level modules for namespacing, classes give you more control over how and where variables are stored, and ought to reduce the number of global variables you have laying around, which is a worthwhile cause in and of itself. It'd take a bit of work, but it might be worth refactoring your various backends to share a common class, de-duplicating code amongst them. This would give you the same API across modules, which is something I had to do [here](https://github.com/itdaniher/torrench/commit/a83c7693d0854ef1583a8eba0f1ed6a8bcd7e737) across KAT/TPB for my purposes.

A possible feature:

For my needs, I just need an outputted list of magnet links for a given query. I added this to [Torrench](https://github.com/itdaniher/torrench/blob/master/torrench/Torrench.py#L68) and I'm pretty happy with the result.

If any of these thoughts / suggestions are of interest, I'd be happy to open a PR for the relevant commits. I'm likely to keep playing with Torrench, you can keep an eye on my patches [on my fork, here.](https://github.com/itdaniher/torrench/commits/master)

Happy hacking!
Ian

**Comment by kryptxy** [comment]
Hi Ian, 
Firstly, Thank you for showing interest in this project.
Being a python beginner, these suggestiins are another learning step for me, so thank you! 

Lets begin:
1. Thanks for PEP8 ( and autopep8). Didn't really gave a thought about it. I'll update entire code to this.
2. Destructuring of dictionaries is great. PR yes!
3. I'll look into python ints as indexes.
4. About classes: I have it on my todo, but it would take me some time (a few days) to get this working. Many functions are common to all modules, and will be required in future modules too (eg. ```http_request()```). So managing them with classes would be nice. Will try to get them ASAP.
5. I'll look into magnets list output. Sounds interesting.

Thank you for these suggestions. I'll keep myself up with your patches. Feel free to post any issues you face, or you think can be improved. I am all ears.

**Comment by itdaniher** [comment]
I opened PRs #9 for formatting and #10 reducing the number of lines by a few.

I can open up a PR for issue number 5, which I implemented [here](https://github.com/itdaniher/torrench/commit/553bba240a85676d3811434ad0130823688f8f44)

Cheers!

**Comment by itdaniher** [comment]
Closing as the most of it's been addressed. Cheers!
